kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: wasp-agent
  labels:
    app: wasp
    tier: node
spec:
  selector:
    matchLabels:
      name: wasp
  template:
    metadata:
      annotations:
        description: >-
          Configures swap for workloads
      labels:
          name: wasp
    spec:
      restartPolicy: Always
      serviceAccountName: wasp
      serviceAccount: wasp
      hostPID: true
      hostUsers: true
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: wasp-agent
          image: >-
            quay.io/openshift-virtualization/wasp-agent:v0.0.10
          imagePullPolicy: Always
          env:
          - name: "FSROOT"
            value: "/host"
          - name: "SWAPPINESS"
            value: "5"
          - name: "NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: "spec.nodeName"
          - name: "DRY_RUN"
            value: "false"
          resources:
            requests:
              cpu: 100m
              memory: 50M
          securityContext:
            privileged: true
          volumeMounts:
          - name: hostopt
            mountPath: "/host/opt"
          - name: hostproc
            mountPath: "/host/proc"
          - name: hostetc
            mountPath: "/host/etc"
          - name: hostrun
            mountPath: "/host/run"
          - name: hostsys
            mountPath: "/host/sys"
          - name: hosttmp
            mountPath: "/host/tmp"
      volumes:
      - name: hostproc
        hostPath:
          path: "/proc"
      - name: hostopt
        hostPath:
          path: "/opt"
      - name: hostetc
        hostPath:
          path: "/etc"
      - name: hostrun
        hostPath:
          path: "/run"
      - name: hostsys
        hostPath:
          path: "/sys"
      - name: hosttmp
        hostPath:
          path: "/tmp"
      priorityClassName: system-node-critical
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 0
status: {}
